apps:
  - script: dist/index.js
    name: 'BO Trading Api Calculator'
    watch: ['dist']
    ignore_watch: ['node_modules', 'dist/logs']
    env_dev:
      NODE_ENV: dev
    env_test:
      NODE_ENV: test
    env_staging:
      NODE_ENV: staging
    env_production:
      NODE_ENV: production
